### ISSUE TITLE
【Rails】フッターの最下部に色が付けられない　または、エラーが解決できない

### ISSUE THREAD

**Issue by sice11** [sice11/playstation_rails#1]
【したいこと】
以下の画像のような表示を行いたい
![無題](https://user-images.githubusercontent.com/61615289/86566958-7fa12e00-bfa5-11ea-8e7e-87c33593f241.png)

【現状】
```
inline-block is ignored due to the float. If 'float' has a value other than 'none', the box is floated and 'display' is treated as 'block'
```
というエラーが以下の箇所に出ている。
https://github.com/sice11/playstation_rails/blob/3f812b86dafef23a073955d403749657260fb470/app/assets/stylesheets/home.scss#L55

![無題1](https://user-images.githubusercontent.com/61615289/86567514-782e5480-bfa6-11ea-9432-83ed3051cd80.png)

【実行した対応】
https://github.com/sice11/playstation_rails/blob/3f812b86dafef23a073955d403749657260fb470/app/assets/stylesheets/home.scss#L54-L61
にある
```
float: right;
```
の記述を削除

https://github.com/sice11/playstation_rails/blob/3f812b86dafef23a073955d403749657260fb470/app/assets/stylesheets/home.scss#L48-L52
こちらのコメントアウトをはずす。

→結果
ページの最下部に空白ができた。

**Comment by good1luck21** [comment]
```css
position: absolute;/*←絶対位置*/
bottom: 0; /*下に固定*/
```

上記で大丈夫です！
