### ISSUE TITLE
ルートの書き方直しましょう

### ISSUE THREAD

**Issue by good1luck21** [sice11/playstation_rails#4]
https://github.com/sice11/playstation_rails/blob/785ca6e726ffef1b8198085b97999f776dadd3b5/config/routes.rb#L2-L7

```ruby
get '/' => 'XXX#YYYY' # あまり好ましくない書き方
root 'XXX#YYYY' # このように書きましょう。
```

上記以外にも指摘事項があるので、下記参考にしてください。
```ruby
get "posts/:id" => "posts#show" # これも好ましくない
get "posts/:id", to: "posts#show", as: 'post_show' # 名前付きrootの書き方をしましょう。
```
参考URL：https://railsguides.jp/routing.html#rails%E3%83%AB%E3%83%BC%E3%82%BF%E3%83%BC%E3%81%AE%E7%9B%AE%E7%9A%84

**Comment by sice11** [comment]
先日の指摘分ですね。
ありがとうございます。
現在対応中です。

～メモ～
git comment
issue#4対応 1-1

**Comment by sice11** [comment]
～メモ～
link toの書き方
```
link_to "表示名",URL
```
の書き方を使って、今回の対応の場合、
```
link_to "表示名", as以下を記入
```
とする。
as以下の記入の部分に関して、
https://github.com/sice11/playstation_rails/blob/b48c5904c18356380a71c3f5851256796449d6f1/config/routes.rb#L7
例えばこの部分。

as以下は「about」としているので、
link_toの最後の部分は、
about_path(@about)
とする。

**Comment by sice11** [comment]
【issues#4 1-2】
routes.rbの投稿一覧の表示がうまくいきません。
どの箇所を修正したらいいでしょうか？

![image](https://user-images.githubusercontent.com/61615289/87263423-17e46900-c4f8-11ea-8b28-40903a4099b5.png)
https://github.com/sice11/playstation_rails/blob/c4ed709c83919dd1375377da3ceacf78224bea4e/config/routes.rb#L4
https://github.com/sice11/playstation_rails/blob/c4ed709c83919dd1375377da3ceacf78224bea4e/app/views/posts/index.html.erb#L5

**Comment by good1luck21** [comment]
5行目の@post.idがおかしいですね。
今each文で繰り返しているので、変数名は何でしょう？

**Comment by sice11** [comment]
post.id
ですね。
ありがとうございます。
うまくいきました。
