### ISSUE TITLE
【Rails】編集画面追加

### ISSUE THREAD

**Issue by sice11** [sice11/playstation_rails#6]
編集画面を追加しようとしているのですが、
うまくいきません。

具体的にはおそらく、
playstation\app\views\posts\edit.html.erb
の以下の部分の記述がおかしいからかな、と思っているのですが、どのように修正したらよろしいでしょうか？
```
    <%= form_for @post, url: posts_update_path() do |f| %>
        <%= f.text_area :content, size:"30*10" %><br>
        <%= f.submit "保存" %>
    <% end %>

```

実行した場合、
下記のようなrouting errorが出ます。
![image](https://user-images.githubusercontent.com/61615289/87733906-0bb81e80-c80c-11ea-93ad-ed0a75af1165.png)

**Comment by good1luck21** [comment]
https://github.com/sice11/playstation_rails/blob/8f542db543b1dcd24725833b8660dc067b768039/config/routes.rb#L13
編集画面の記述の仕方は間違っていません！
上記のroutes.rbの記載に誤りがあります！

**Comment by sice11** [comment]
追加分
編集内容がnilになってしまいます。
どのように修正したらよろしいでしょうか？
```
irb(main):002:0> post2 = Post.find_by(id: 12)
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 12], ["LIMIT", 1]]
=> #<Post id: 12, content: nil, created_at: "2020-07-14 13:45:46", updated_at: "2020-07-19 11:27:55">
```

**Comment by good1luck21** [comment]
```ruby
def update
  @post = Post.find_by(id: params[:id])
  p '===================================================='
  p params
  p @post.content
  p '===================================================='
  @post.content = params[:content]
  if @post.save
    redirect_to posts_index_path
  end
end
```

上記のようにパラメーターとfind_byした結果をコンソール画面に出力してみてください。
パラメーターを取得できていないので、nilになっています。
本ヒントで解決できなかった際は再度ご連絡ください！

**Comment by good1luck21** [comment]
@post = Post.find_by(id: params[:post][:id])
とやらないとダメですね。

**Comment by sice11** [comment]
～メモ～
【実施後】
![image](https://user-images.githubusercontent.com/61615289/88164846-acb13a00-cc4f-11ea-83fa-f2b7bac57bde.png)

**Comment by sice11** [comment]
参照↓
https://github.com/sice11/post_app/wiki/%E8%BA%93%E3%81%8D%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88

【解決方法】
①@post.content = params[:content]
の部分のパラメータの取得方法に問題あり。
今回は、form_for（モデルを意識した取得）を活用しているため、
パラメータの取得にも、モデル（今回はpost）を入れる必要がある。
つまり、

```
@post.content = params[:post][:content]
```
とする必要がある。

②strongパラメータを活用
